name: Angular Jobs push Master
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
  pull_request:
jobs:
  pipeline:
    name: Angular Jobs pipeline for push on master
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    timeout-minutes: 40
    env:
      NODE_VERSION: 12.13.1
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
      NG_CLI_ANALYTICS: false
    steps:
      # Setup du contexte d'exécution, node pour le front
      # Import des packages avec la version associé. Si besoin d'une evolution tous les workflows doivent être modifiés
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      # Import des packages nodes
      - name: Install node.js packages
        run: npm install
      # Package du livrable, ici au format jar, mais peut être fait en war avec la commande ./gradlew bootWar...
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}

